export enum TrainType {
  EKSEKUTIF = "EKSEKUTIF",
  BISNIS = "BISNIS",
  EKONOMI = "EKONOMI",
  LUXURY = "LUXURY",
  SLEEPER = "SLEEPER",
}

export enum SeatClass {
  EKSEKUTIF = "EKSEKUTIF",
  BISNIS = "BISNIS",
  EKONOMI = "EKONOMI",
  PREMIUM_EKONOMI = "PREMIUM_EKONOMI",
}

export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
  USED = "USED",
  EXPIRED = "EXPIRED",
}

export enum OrderStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  CONFIRMED = "CONFIRMED",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  REFUNDED = "REFUNDED"
}

export enum PaymentMethod {
  BANK_TRANSFER = "BANK_TRANSFER",
  CREDIT_CARD = "CREDIT_CARD",
  E_WALLET = "E_WALLET",
  VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT",
  QRIS = "QRIS",
  CASH = "CASH"
}