export enum TrainType {
  EKSEKUTIF = "EKSEKUTIF",
  BISNIS = "BISNIS",
  EKONOMI = "EKONOMI",
  LUXURY = "LUXURY",
  SLEEPER = "SLEEPER",
}

export enum SeatClass {
  EKSEKUTIF = "EKSEKUTIF",
  BISNIS = "BISNIS",
  EKONOMI = "EKONOMI",
  PREMIUM_EKONOMI = "PREMIUM_EKONOMI",
}

export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
  USED = "USED",
  EXPIRED = "EXPIRED",
}

export enum OrderStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  CONFIRMED = "CONFIRMED",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  AUTHORIZED = "AUTHORIZED",
  CAPTURED = "CAPTURED",
  PAID = "PAID",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  EXPIRED = "EXPIRED",
}