FROM postgres:15

ARG PORT
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG DATABASE_URL
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_NAME
ARG JWT_EXPIRES_IN
ARG JWT_REFRESH_IN
ARG XENDIT_PUBLIC_KEY
ARG FRONTEND_URL

ENV PORT=${PORT}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV DATABASE_URL=${DATABASE_URL}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_NAME=${DB_NAME}
ENV JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
ENV JWT_REFRESH_IN=${JWT_REFRESH_IN}
ENV XENDIT_PUBLIC_KEY=${XENDIT_PUBLIC_KEY}
ENV FRONTEND_URL=${FRONTEND_URL}