services:
  redis:
    image: redis:7-alpine
    container_name: skyvix-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
  skyvix:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - DATABASE_URL=${DATABASE_URL}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_NAME=${DB_NAME}
        - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
        - JWT_REFRESH_IN=${JWT_REFRESH_IN}
        - XENDIT_PUBLIC_KEY=${XENDIT_PUBLIC_KEY}
        - FRONTEND_URL=${FRONTEND_URL}
    image: skyvix
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: skyvix_admin
    depends_on: 
      - redis
      
  skyvix_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - DATABASE_URL=${DATABASE_URL}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_NAME=${DB_NAME}
        - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
        - JWT_REFRESH_IN=${JWT_REFRESH_IN}
        - XENDIT_PUBLIC_KEY=${XENDIT_PUBLIC_KEY}
        - FRONTEND_URL=${FRONTEND_URL}
    image: skyvix_dev
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: skyvix_admin_dev
    depends_on:
      - redis

volumes:
  redis_data: